name: xilocanvas
description: Flet Xilocanvas control
repository: https://github.com/MyGithubAccount/xilocanvas/src/flutter/xilocanvas
version: 0.1.0
homepage: https://github.com/MyGithubAccount/xilocanvas

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.0
  flet: 0.26.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
